{{- if .Values.downloadOrchestrator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.downloadOrchestrator.name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.downloadOrchestrator.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.downloadOrchestrator.secrets.mongoUri }}
{{- end }}
---
{{- if .Values.fileSharing.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fileSharing.name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.fileSharing.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.fileSharing.secrets.mongoUri }}
{{- end }}
