apiVersion: v1
kind: Secret
metadata:
  name: download-orchestrator-secrets
  namespace: cse474-prod
  labels:
    app: download-orchestrator
type: Opaque
stringData:
  mongo-uri: mongodb://mongodb:27017/download-orchestrator
