apiVersion: v1
kind: ConfigMap
metadata:
  name: file-quota-config
  namespace: cse474-prod
  labels:
    app: file-quota-service
data:
  port: "3001"
  node-env: "production"
  db-host: "db-file-quota"
  db-port: "5432"
  db-name: "quota_db"
  kafka-broker: "kafka:9092"
  log-level: "info"
