apiVersion: v1
kind: ConfigMap
metadata:
  name: file-sharing-config
  namespace: cse474-prod
  labels:
    app: file-sharing
data:
  port: "3002"
  node-env: "production"
  kafka-brokers: "kafka:9092"
  log-level: "info"
  service-name: "file-sharing"
  jaeger-endpoint: "http://jaeger:14268/api/traces"
  prometheus-port: "9091"
