apiVersion: v1
kind: Secret
metadata:
  name: file-quota-secrets
  namespace: cse474-prod
  labels:
    app: file-quota-service
type: Opaque
# Base64 encoded values: echo -n 'postgres' | base64 → cG9zdGdyZXM=
data:
  db-user: cG9zdGdyZXM=
  db-password: cG9zdGdyZXM=
