apiVersion: v1
kind: ConfigMap
metadata:
  name: presigned-url-config
  namespace: cse474-prod
  labels:
    app: presigned-url-service
data:
  port: "3002"
  node-env: "production"
  db-host: "db-presigned-url"
  db-port: "5432"
  db-name: "url_db"
  storage-gateway-url: "http://storage-gateway:9000"
  log-level: "info"
