apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "config-service.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: config.cse474.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "config-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
