apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-flag-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: flags.cse474.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-flag-service
                port:
                  number: {{ .Values.service.port }}
