apiVersion: v1
kind: Secret
metadata:
  name: feature-flag-service-secret
type: Opaque
data:
  DB_USER: {{ .Values.secrets.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}
