apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service-config
  namespace: cse474-prod
data:
  PORT: "3031"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "config_db"
  KAFKA_BROKER: "kafka:9092"
  KAFKA_CLIENT_ID: "config-service"
  KAFKA_TOPIC: "config.updated"
