apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: cse474-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: ghcr.io/<YOUR_GITHUB_USERNAME>/config-service:latest
          ports:
            - containerPort: 3031
          envFrom:
            - configMapRef:
                name: config-service-config
            - secretRef:
                name: config-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3031
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 3031
            initialDelaySeconds: 10
            periodSeconds: 10
