apiVersion: v1
kind: ConfigMap
metadata:
  name: cse474-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.fileRegistry.env.DB_HOST | quote }}
  DB_USER: {{ .Values.fileRegistry.env.DB_USER | quote }}
  KAFKA_BROKERS: {{ .Values.fileRegistry.env.KAFKA_BROKERS | quote }}
  LOG_LEVEL: {{ .Values.fileRegistry.env.LOG_LEVEL | quote }}
