{{- if .Values.downloadOrchestrator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: download-orchestrator-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: download-orchestrator
type: Opaque
stringData:
  mongo-uri: mongodb://mongodb:27017/download-orchestrator
{{- end }}
