{{- if .Values.fileQuota.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: file-quota-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: file-quota-service
type: Opaque
stringData:
  db-user: {{ .Values.fileQuota.secrets.dbUser | quote }}
  db-password: {{ .Values.fileQuota.secrets.dbPassword | quote }}
{{- end }}
