{{- if .Values.fileSharing.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: file-sharing-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: file-sharing
type: Opaque
stringData:
  mongo-uri: mongodb://mongodb:27017/file-sharing
{{- end }}
