{{- if .Values.presignedUrl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: presigned-url-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: presigned-url-service
type: Opaque
stringData:
  db-user: {{ .Values.presignedUrl.secrets.dbUser | quote }}
  db-password: {{ .Values.presignedUrl.secrets.dbPassword | quote }}
{{- end }}
